services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: amine
      POSTGRES_PASSWORD: amine
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: