"""create_exams_tables

Revision ID: 15097c05c9ef
Revises: 7a7211029b60
Create Date: 2025-05-17 02:02:48.982046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15097c05c9ef'
down_revision: Union[str, None] = '7a7211029b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exam_sessions_user_id_fkey', 'exam_sessions', type_='foreignkey')
    op.drop_column('exam_sessions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('exam_sessions_user_id_fkey', 'exam_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
