"""add_classes_toUsers

Revision ID: 1c41bc3a48d2
Revises: edff5f62053a
Create Date: 2025-05-20 15:49:57.960098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c41bc3a48d2'
down_revision: Union[str, None] = 'edff5f62053a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_class_unique', 'user_class_associations', ['user_id', 'class_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_class_unique', table_name='user_class_associations')
    # ### end Alembic commands ###
