"""add_created_by_to_exams

Revision ID: 46f8cd3f9a0e
Revises: 15097c05c9ef
Create Date: 2025-05-17 02:18:15.250597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f8cd3f9a0e'
down_revision: Union[str, None] = '15097c05c9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exams', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_column('exams', 'created_by')
    # ### end Alembic commands ###
