"""add salle as exams attribute

Revision ID: 5f31235055f9
Revises: e0db0c8e64fc
Create Date: 2025-05-22 00:58:24.996582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f31235055f9'
down_revision: Union[str, None] = 'e0db0c8e64fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('sale', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'sale')
    # ### end Alembic commands ###
