"""initial

Revision ID: 7a864da28f7a
Revises: 
Create Date: 2025-05-23 15:07:41.178541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a864da28f7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('sale', sa.String(length=20), nullable=True))
    op.add_column('exams', sa.Column('fraud_evidence', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'fraud_evidence')
    op.drop_column('exams', 'sale')
    # ### end Alembic commands ###
