"""rename_student_id_to_institutional_id

Revision ID: 94c958ee4fa4
Revises: 
Create Date: 2025-05-11 23:29:52.447978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c958ee4fa4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('institutional_id', sa.String(length=50), nullable=True))
    op.drop_constraint('users_student_id_number_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['institutional_id'])
    op.drop_column('users', 'student_id_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_id_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_student_id_number_key', 'users', ['student_id_number'])
    op.drop_column('users', 'institutional_id')
    # ### end Alembic commands ###
