"""remove_created_by_from_exams

Revision ID: cad90f1ff3ab
Revises: 46f8cd3f9a0e
Create Date: 2025-05-17 02:22:12.630801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad90f1ff3ab'
down_revision: Union[str, None] = '46f8cd3f9a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exams_created_by_fkey', 'exams', type_='foreignkey')
    op.drop_column('exams', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('exams_created_by_fkey', 'exams', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
