"""remove_user_activation

Revision ID: edff5f62053a
Revises: 2a671c6bc0f9
Create Date: 2025-05-19 13:22:06.131378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edff5f62053a'
down_revision: Union[str, None] = '2a671c6bc0f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exam_sessions_id', table_name='exam_sessions')
    op.drop_table('exam_sessions')
    op.add_column('exams', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('exams', sa.Column('fraud_status', sa.Text(), nullable=True))
    op.drop_column('exams', 'exam_type')
    op.drop_column('exams', 'security_level')
    op.drop_column('exams', 'duration')
    op.drop_column('exams', 'instructions')
    op.drop_column('exams', 'location')
    op.drop_column('exams', 'is_active')
    op.drop_column('exams', 'total_marks')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('total_marks', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('exams', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('exams', sa.Column('security_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('exam_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('exams', 'fraud_status')
    op.drop_column('exams', 'status')
    op.create_table('exam_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('suspicious_activities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('final_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name='exam_sessions_exam_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exam_sessions_pkey')
    )
    op.create_index('ix_exam_sessions_id', 'exam_sessions', ['id'], unique=False)
    # ### end Alembic commands ###
